# Generated by Django 4.2.3 on 2023-09-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
