# Generated by Django 4.2.3 on 2023-09-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
